### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by TerryMay** [ahasbini/AndroidOpenCVGradlePlugin#1]
Following the directions and the build will fail because the sample project tried to access the plugin before it is place.  

I fixed the issue by first commenting out the line 'include 'sample'" in the gradle.settings the first time that ./gradlew :plugin:publishToMavenLocal is run

EDIT: I thought that I fixed but it has now failed with a new error, I'll list it here even though it might be a different issue:

```Caused by: com.ahasbini.tools.androidopencv.PluginException: Unable to create/write build scripts.
        Caused by java.lang.IllegalArgumentException: URI is not hierarchical```

**Comment by ahasbini** [comment]
> Following the directions and the build will fail because the sample project tried to access the plugin before it is place.

That actually makes sense! Should look for a workaround for that, maybe by using the `buildSrc`. But as you said, removing ```include 'sample'``` for the first time and running ```./gradlew :plugin:publishToMavenLocal``` successfully, you should be able to re-```include 'sample'``` after that and building the project should work just fine.

> EDIT: I thought that I fixed but it has now failed with a new error, I'll list it here even though it might be a different issue:
>        ```Caused by java.lang.IllegalArgumentException: URI is not hierarchical```

Try running ```./gradlew --stacktrace --console=plain :plugin:publishToMavenLocal``` and post the complete output here.

**Comment by ahasbini** [comment]
New release v0.1.3-dev has been published on Gradle Plugins Portal and can be [here](https://plugins.gradle.org/plugin/com.ahasbini.android-opencv-gradle-plugin). It contains quite some changes and improvements.
