### ISSUE TITLE
OpenCV sourceforge links incorrect?

### ISSUE THREAD

**Issue by alungoodger** [ahasbini/AndroidOpenCVGradlePlugin#2]
Having setup the plugin as described, I get the following error when building the project:

ERROR: Not Found (HTTP status code: 404, URL: https://sourceforge.net/projects/opencvlibrary/files/3.4.3/opencv-3.4.3-android-sdk.zip)

As suggested by the error message the link that is being used does not seem to work.

The download link that is used when navigating manually via a browser is:

https://sourceforge.net/projects/opencvlibrary/files/opencv-android/3.4.3/opencv-3.4.3-android-sdk.zip/download

But that redirects to another site for the actual download, in my case:

https://cfhcable.dl.sourceforge.net/project/opencvlibrary/opencv-android/3.4.3/opencv-3.4.3-android-sdk.zip

**Comment by ahasbini** [comment]
True, this is a problem that I'm still trying to solve where some of the older versions of OpenCV are published in a different path format than the newer ones.

For now, there's an option which can be used to overcome this issue. Use the below configuration for the `androidOpenCV` block:

```groovy
androidOpenCV {
    version '3.4.3'
    url 'https://sourceforge.net/projects/opencvlibrary/files/opencv-android/3.4.3/opencv-3.4.3-android-sdk.zip'
}
```

Note that the `url` option has been marked as deprecated for now and will be removed when a proper fix is implemented in the future. Feel free to use to make the plugin work for now.

**Comment by ahasbini** [comment]
Btw, version 3.4.4 and above versions are published the right way the plugin expects, so if there aren't any problems with using versions newer than 3.4.3 then there's no need to have `url` specified.

**Comment by alungoodger** [comment]
Thanks, the url option seems like a suitable solution to the issue... maybe its worth mentioning in README.md?

FYI I was only experimenting with using an older version of opencv because I could not get the plugin to work (compile opencv successfully) with the newer versions :(   I have got further with version 4.1.2, but only by manually making some changes that I suspect should not be required. that said, Android studio/gradle/etc configuration is not really my area of expertise. Is there any kind of forum for this plugin where I can discuss/get help with my problems?

**Comment by ahasbini** [comment]
>Thanks, the url option seems like a suitable solution to the issue... maybe its worth mentioning in README.md?

I had it mentioned in the older versions of the plugin but because of the deprecation decision I removed it. This will hopefully drive me to come up with a proper implementation that will replace the `url` option soon.

>FYI I was only experimenting with using an older version of opencv because I could not get the plugin to work (compile opencv successfully) with the newer versions :( I have got further with version 4.1.2, but only by manually making some changes that I suspect should not be required. that said, Android studio/gradle/etc configuration is not really my area of expertise. Is there any kind of forum for this plugin where I can discuss/get help with my problems?

Well there isn't an official forum for this plugin yet but you can just open them as issues here, include any logs, pieces of code or useful info and it'll be a discussion to work out the problems. I'd be happy to help in issues that are related to plugin as this will in turn improve the plugin as well! :)

Since the provided solution to this issue works, I'll mark this issue as closed. Feel free to comment again or open a new issue(s) if needed.
